import AppKit

/// Inserts text into the frontmost app: pasteboard snapshot → write transcript
/// → synthetic ⌘V → restore the snapshot later if nothing else touched the
/// pasteboard. Under secure input, leaves the text on the clipboard instead.
public final class TextInserter {
    public enum Outcome: Equatable {
        case pasted
        case copiedOnlySecureInput
    }

    private let restoreDelay: TimeInterval
    private let secureClearDelay: TimeInterval
    private let secureInputCheck: () -> Bool

    /// nspasteboard.org markers: clipboard managers (Maccy, Raycast, Alfred,
    /// Paste…) skip items carrying these, and Universal Clipboard treats them as
    /// transient — so a dictated utterance isn't archived into a permanent
    /// third-party history or synced to the user's other devices.
    public static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    public init(restoreDelay: TimeInterval = 0.6,
                secureClearDelay: TimeInterval = 60,
                secureInputCheck: @escaping () -> Bool = { isSecureInputActive() }) {
        self.restoreDelay = restoreDelay
        self.secureClearDelay = secureClearDelay
        self.secureInputCheck = secureInputCheck
    }

    public func insert(_ text: String, into pasteboard: NSPasteboard = .general) -> Outcome {
        let snapshot = Self.snapshot(of: pasteboard)
        pasteboard.clearContents()
        pasteboard.writeObjects([Self.stagedItem(for: text)])
        let changeCountAfterWrite = pasteboard.changeCount

        if secureInputCheck() {
            // Synthetic ⌘V can't land in a secure field, so the user pastes it
            // themselves — but a dictated password must not sit on the clipboard
            // forever. Restore the prior clipboard after a delay (evicting the
            // secret) unless the user has replaced it first.
            DispatchQueue.main.asyncAfter(deadline: .now() + secureClearDelay) {
                Self.restore(snapshot, to: pasteboard, ifChangeCountStill: changeCountAfterWrite)
            }
            return .copiedOnlySecureInput
        }

        usleep(15_000) // let the pasteboard write settle before the paste keystroke
        Self.postCommandV()

        DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay) {
            Self.restore(snapshot, to: pasteboard, ifChangeCountStill: changeCountAfterWrite)
        }
        return .pasted
    }

    // MARK: pasteboard snapshot/restore (parameterized for tests)

    /// The dictated text staged as a concealed, auto-generated item.
    public static func stagedItem(for text: String) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString(text, forType: concealedType)
        item.setString("1", forType: autoGeneratedType)
        return item
    }

    /// Fresh copies of every item — NSPasteboardItems can't be re-staged once
    /// their pasteboard is cleared.
    public static func snapshot(of pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) {
                    copy.setData(data, forType: type)
                }
            }
            return copy
        }
    }

    public static func restore(_ snapshot: [NSPasteboardItem], to pasteboard: NSPasteboard,
                               ifChangeCountStill expected: Int) {
        guard shouldRestore(expected: expected, current: pasteboard.changeCount) else { return }
        pasteboard.clearContents()
        if !snapshot.isEmpty {
            pasteboard.writeObjects(snapshot)
        }
    }

    /// Restore only if nothing (including the user copying something new)
    /// touched the pasteboard since our write.
    public static func shouldRestore(expected: Int, current: Int) -> Bool {
        expected == current
    }

    // MARK: keystroke synthesis

    private static func postCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let vKey: CGKeyCode = 9 // kVK_ANSI_V
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false) else {
            return
        }
        // Explicit flags on both events override any physical modifier state.
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
    }
}
