#!/usr/bin/env bash
#
# install_kyutai.sh — provision the local Kyutai STT streaming runtime for Murmur.
#
#   1. builds moshi-server (Rust) with Metal support → ~/.cargo/bin/moshi-server
#   2. writes the STT server config (1b en+fr) → Application Support/Murmur/kyutai/
#
# The ~2.4 GB model is NOT downloaded here — moshi-server auto-fetches the
# `hf://…` weights into ~/.cache/huggingface/hub on first launch.
#
# Prereqs (Apple Silicon, Command Line Tools): `brew install rust cmake`.
# Re-run with FORCE=1 to rebuild an already-installed binary.
set -euo pipefail

APP_SUPPORT="$HOME/Library/Application Support/Murmur/kyutai"
CONFIG="$APP_SUPPORT/moshi-stt.toml"
BIN="$HOME/.cargo/bin/moshi-server"

echo "==> Checking build prerequisites"
command -v cargo >/dev/null || { echo "ERROR: cargo not found — run: brew install rust"; exit 1; }
command -v cmake >/dev/null || { echo "ERROR: cmake not found — run: brew install cmake"; exit 1; }
echo "    cargo: $(cargo --version)"
echo "    free disk: $(df -h "$HOME" | awk 'NR==2{print $4}')"

# moshi-server depends on pyo3, which supports Python ≤3.13. If the default
# python3 is newer (e.g. 3.14), pyo3's build fails — point it at an installed
# 3.12/3.13 (the same `brew install python@3.12` the upstream installer wants).
if [ -z "${PYO3_PYTHON:-}" ]; then
  for cand in python3.12 python3.13; do
    if command -v "$cand" >/dev/null 2>&1; then export PYO3_PYTHON="$(command -v "$cand")"; break; fi
  done
fi
if [ -n "${PYO3_PYTHON:-}" ]; then
  echo "    PYO3_PYTHON: $PYO3_PYTHON"
else
  echo "    note: no python3.12/3.13 found; if cargo install fails on pyo3, run: brew install python@3.12"
fi

# CMake ≥4 removed compatibility with the old cmake_minimum_required(<3.5) that
# sentencepiece-sys' bundled C++ declares; allow it to configure anyway.
export CMAKE_POLICY_VERSION_MINIMUM="${CMAKE_POLICY_VERSION_MINIMUM:-3.5}"

if [ -x "$BIN" ] && [ "${FORCE:-0}" != "1" ]; then
  echo "==> moshi-server already present at $BIN (FORCE=1 to rebuild)"
else
  echo "==> Building moshi-server with Metal (10–20 min, large Rust compile)…"
  # --locked: use the crate's shipped Cargo.lock. A fresh re-resolve pulls
  # incompatible transitive deps (brotli/alloc-no-stdlib) that fail to compile.
  # --version: pin the crate so every install builds the same audited source
  # (an unpinned `cargo install` runs whatever build.rs is latest on crates.io).
  cargo install --locked --version "${MOSHI_VERSION:-0.6.4}" --features metal moshi-server
fi

# A random per-install token instead of the shipped "public_token". The app
# binds moshi-server to 127.0.0.1 (see KyutaiStreamingEngine.serverArguments), so
# this is defence in depth — but a published constant token is never a secret.
TOKEN="$(openssl rand -hex 24)"

echo "==> Writing STT config → $CONFIG"
mkdir -p "$APP_SUPPORT/static" "$APP_SUPPORT/logs"
cat > "$CONFIG" <<EOF
# Generated by scripts/install_kyutai.sh — Kyutai STT 1b en+fr, single-user.
static_dir = "$APP_SUPPORT/static/"
log_dir = "$APP_SUPPORT/logs/"
instance_name = "murmur"
authorized_ids = ["$TOKEN"]

[modules.asr]
path = "/api/asr-streaming"
type = "BatchedAsr"
lm_model_file = "hf://kyutai/stt-1b-en_fr-candle/model.safetensors"
text_tokenizer_file = "hf://kyutai/stt-1b-en_fr-candle/tokenizer_en_fr_audio_8000.model"
audio_tokenizer_file = "hf://kyutai/stt-1b-en_fr-candle/mimi-pytorch-e351c8d8@125.safetensors"
asr_delay_in_tokens = 6
batch_size = 2          # single-user; official 64 pre-allocates ~6 GB KV cache
conditioning_learnt_padding = true
temperature = 0.0

[modules.asr.model]
audio_vocab_size = 2049
text_in_vocab_size = 8001
text_out_vocab_size = 8000
audio_codebooks = 32

[modules.asr.model.transformer]
d_model = 2048
num_heads = 16
num_layers = 16
dim_feedforward = 8192
causal = true
norm_first = true
bias_ff = false
bias_attn = false
context = 750
max_period = 100000
use_conv_block = false
use_conv_bias = true
gating = "silu"
norm = "RmsNorm"
positional_embedding = "Rope"
conv_layout = false
conv_kernel_size = 3
kv_repeat = 1
max_seq_len = 40960

[modules.asr.model.extra_heads]
num_heads = 4
dim = 6
EOF

# Point the app's config at this token + config path so it can authenticate to
# its own server. Refuses to touch an existing config.json it can't parse (never
# clobber a hand-edited file); preserves all other keys; writes 0600.
echo "==> Updating ~/.config/murmur/config.json (kyutaiApiKey, kyutaiConfigPath)"
python3 - "$TOKEN" "$CONFIG" <<'PY'
import json, os, sys
token, cfg_path = sys.argv[1], sys.argv[2]
p = os.path.expanduser("~/.config/murmur/config.json")
os.makedirs(os.path.dirname(p), mode=0o700, exist_ok=True)
try:
    with open(p) as f:
        data = json.load(f)
except FileNotFoundError:
    data = {}
except Exception as e:
    sys.stderr.write("ERROR: %s is not valid JSON (%s); not overwriting.\n"
                     "       Set \"kyutaiApiKey\" to the token below by hand.\n" % (p, e))
    sys.exit(1)
data["kyutaiApiKey"] = token
data["kyutaiConfigPath"] = cfg_path
fd = os.open(p, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, "w") as f:
    json.dump(data, f, indent=2, sort_keys=True)
os.chmod(p, 0o600)
PY

echo "==> Done."
echo "    binary: $BIN"
echo "    config: $CONFIG"
echo "    token : $TOKEN  (written to config.json)"
echo "    launch: \"$BIN\" worker --config \"$CONFIG\" --addr 127.0.0.1 --port 8090"
echo "    (the 1b model ~2.4 GB downloads on first launch)"
